//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public Nullable<int> CusID { get; set; }
        public Nullable<int> CofID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> Orderdate { get; set; }
        public Nullable<decimal> Totalprice { get; set; }
        public string OrderNumber { get; set; }
    
        public virtual Coffee Coffee { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
